const TYPES = {
    AppConfig: Symbol.for('AppConfig'),
    WinstonLogger: Symbol.for('WinstonLogger'),
    Logger: Symbol.for('Logger'),
    BookRepository: Symbol.for("BookRepository"),
    AuthorRepository: Symbol.for("AuthorRepository"),
    ReadAuthorListHandler: Symbol.for("ReadAuthorListHandler"),
    ReadAuthorHandler: Symbol.for("ReadAuthorHandler"),
    CreateAuthorCommandHandler: Symbol.for("CreateAuthorCommandHandler"),
    ReadBookListHandler: Symbol.for("ReadBookListHandler"),
    ReadBookHandler: Symbol.for("ReadBookHandler"),
    CreateBookCommandHandler: Symbol.for("CreateBookCommandHandler"),
    AuthorController: Symbol.for("AuthorController"),
    BookController: Symbol.for("BookController"),
    BookPublishController: Symbol.for("BookPublishController"),
    BookClassifyController: Symbol.for("BookClassifyController"),
    CosmosClient: Symbol.for('CosmosClient'),
    BookContainer: Symbol.for('BookContainer'),
    AuthorContainer: Symbol.for('AuthorContainer'),
    CreateBookValidator: Symbol.for('CreateBookValidator'),
    UpdateBookValidator: Symbol.for('UpdateBookValidator'),
    DeleteBookValidator: Symbol.for('DeleteBookValidator'),
    ClassifyBookValidator: Symbol.for('ClassifyBookValidator'),
    PublishBookValidator: Symbol.for('PublishBookValidator'),
    UpdateBookCommandHandler: Symbol.for("UpdateBookCommandHandler"),
    DeleteBookCommandHandler: Symbol.for("DeleteBookCommandHandler"),
    PublishBookCommandHandler: Symbol.for("PublishBookCommandHandler"),
    UpdatePublicationCommandHandler: Symbol.for("UpdatePublicationCommandHandler"),
    ClassifyBookCommandHandler: Symbol.for("ClassifyBookCommandHandler"),
    UpdateClassificationCommandHandler: Symbol.for("UpdateClassificationCommandHandler"),
    HealthService: Symbol.for("HealthService"),
    HealthController: Symbol.for("HealthController"),
};

export default TYPES;
